
// Generated by Cadence Encounter(R) RTL Compiler RC13.10 - v13.10-s006_1

module flipflop_1_100_g(CLK, D, Q);
  input CLK, D;
  output Q;
  wire CLK, D;
  wire Q;
  fflopd Q_reg(.CK (CLK), .D (D), .Q (Q));
endmodule

