
// Generated by Cadence Encounter(R) RTL Compiler RC13.10 - v13.10-s006_1

module flipflop_1_ar1_0_100_g(CLK, RST, D, Q);
  input CLK, RST, D;
  output Q;
  wire CLK, RST, D;
  wire Q;
  wire n_1;
  flopdrs Q_reg(.R (n_1), .S (1'b1), .CK (CLK), .D (D), .Q (Q));
  inv1 g4(.A (RST), .Y (n_1));
endmodule

